# Generated by Django 3.2.3 on 2025-06-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoprecipes',
            options={'ordering': ('id',), 'verbose_name': 'список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
    ]
