# Generated by Django 3.2.3 on 2025-06-03 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subs', '0003_auto_20250530_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriptions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='users.profile', verbose_name='Подписки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(fields=('user', 'subscriptions'), name='unique_subscription'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('subscriptions')), _negated=True), name='prevent_self_subscription'),
        ),
    ]
