# Generated by Django 3.2.3 on 2025-06-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0004_auto_20250603_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('-id',), 'verbose_name': 'подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
