# Generated by Django 3.2.3 on 2025-06-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0006_alter_subscriber_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('user',), 'verbose_name': 'подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
