# Generated by Django 3.2.3 on 2025-06-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
