# Generated by Django 3.2.3 on 2025-06-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created_at', 'name'), 'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
